window.MVP_ACTIONS_REAL = [
  {
    "action_id": "action-2026-04-yamada-mai-transport-001",
    "representative_id": "yamada_mai",
    "representative_name": "山田摩衣",
    "action_date": "2026-04-02",
    "action_month": "2026-04",
    "issue_id": "transport",
    "issue_label": "交通行人",
    "action_type": "質詢",
    "title": "追問板橋醫療園區停車場補助與收益歸屬",
    "summary": "針對板橋醫療園區招商案中的長照住宿機構與 280 席停車場補助，追問 BTO 預算配置、可行性評估財務分析、施工前後停車位方案、停車費收益歸屬與政府回收機制，並要求衛生局就廠商補助 9.1 億詳細內容進行專案報告。",
    "alignment": "符合",
    "weight": "3",
    "source_id": "ntpc-council-youtube-1150402",
    "source_name": "新北市議會 YouTube 議事影音 ASR 初稿",
    "source_url": "https://www.youtube.com/watch?v=LYxQ5yS4Xrg&t=5668s",
    "source_file": "data/frames/ntpc-council-youtube-1150402-012932-013932/frame-0456.png",
    "review_status": "speaker_confirmed",
    "notes": "由 faster-whisper 逐字稿候選轉入；畫面人工確認議員山田摩衣；逐字稿證據見 action_evidence_from_transcripts.csv；內容同時涉及板橋醫療園區、長照住宿機構與停車補助；已補完同場質詢至 6139 秒，後續可支援多議題標籤 care|transport"
  },
  {
    "action_id": "action-2026-06-lin-guochun-justice-001",
    "representative_id": "lin_guochun",
    "representative_name": "林國春",
    "action_date": "2026-06-05",
    "action_month": "2026-06",
    "issue_id": "justice",
    "issue_label": "治安詐騙",
    "action_type": "新聞稿",
    "title": "提醒暑期打工與投資詐騙防範",
    "summary": "對應暑期打工與投資詐騙風險，提醒民眾留意詐騙手法與治安防範。",
    "alignment": "符合",
    "weight": "2",
    "source_id": "mvp-seed-demo",
    "source_name": "MVP 種子資料（待查證）",
    "source_url": "",
    "source_file": "",
    "review_status": "needs_review",
    "notes": "由 MVP 示範資料移入 2026-06 第一批行動資料；需補正式來源連結"
  },
  {
    "action_id": "action-2026-06-liu-meifang-care-001",
    "representative_id": "liu_meifang",
    "representative_name": "劉美芳",
    "action_date": "2026-06-12",
    "action_month": "2026-06",
    "issue_id": "care",
    "issue_label": "長照社福",
    "action_type": "質詢",
    "title": "要求提高社區關懷據點服務彈性",
    "summary": "針對長照與家庭照顧需求，要求提高社區關懷據點服務彈性與可近性。",
    "alignment": "符合",
    "weight": "3",
    "source_id": "mvp-seed-demo",
    "source_name": "MVP 種子資料（待查證）",
    "source_url": "",
    "source_file": "",
    "review_status": "needs_review",
    "notes": "由 MVP 示範資料移入 2026-06 第一批行動資料；需補正式來源連結"
  },
  {
    "action_id": "action-2026-06-tai-weishan-education-001",
    "representative_id": "tai_weishan",
    "representative_name": "戴瑋姍",
    "action_date": "2026-06-03",
    "action_month": "2026-06",
    "issue_id": "education",
    "issue_label": "托育教育",
    "action_type": "記者會",
    "title": "公布暑期兒少活動與弱勢學習支持缺口",
    "summary": "針對暑期托育與弱勢學習支持需求，整理兒少活動與資源缺口。",
    "alignment": "符合",
    "weight": "2",
    "source_id": "mvp-seed-demo",
    "source_name": "MVP 種子資料（待查證）",
    "source_url": "",
    "source_file": "",
    "review_status": "needs_review",
    "notes": "由 MVP 示範資料移入 2026-06 第一批行動資料；需補正式來源連結"
  },
  {
    "action_id": "action-2026-06-yamada-mai-energy-001",
    "representative_id": "yamada_mai",
    "representative_name": "山田摩衣",
    "action_date": "2026-06-08",
    "action_month": "2026-06",
    "issue_id": "energy",
    "issue_label": "市場商圈",
    "action_type": "社群發文",
    "title": "整理端午商圈活動與人流改善建議",
    "summary": "整理端午期間商圈活動與人流改善建議，回應市場商圈活化與步行環境議題。",
    "alignment": "部分符合",
    "weight": "1",
    "source_id": "mvp-seed-demo",
    "source_name": "MVP 種子資料（待查證）",
    "source_url": "",
    "source_file": "",
    "review_status": "needs_review",
    "notes": "由 MVP 示範資料移入 2026-06 第一批行動資料；需補正式來源連結"
  },
  {
    "action_id": "action-2026-06-huang-shujun-housing-001",
    "representative_id": "huang_shujun",
    "representative_name": "黃淑君",
    "action_date": "2026-06-05",
    "action_month": "2026-06",
    "issue_id": "housing",
    "issue_label": "居住都更",
    "action_type": "新聞稿",
    "title": "公布租屋安全與違規隔間檢核清單",
    "summary": "針對租屋安全與違規隔間風險，公布檢核清單並提醒居住安全注意事項。",
    "alignment": "符合",
    "weight": "2",
    "source_id": "mvp-seed-demo",
    "source_name": "MVP 種子資料（待查證）",
    "source_url": "",
    "source_file": "",
    "review_status": "needs_review",
    "notes": "由 MVP 示範資料移入 2026-06 第一批行動資料；需補正式來源連結"
  },
  {
    "action_id": "action-2026-06-shih-yiyou-care-001",
    "representative_id": "shih_yiyou",
    "representative_name": "石一佑",
    "action_date": "2026-06-11",
    "action_month": "2026-06",
    "issue_id": "care",
    "issue_label": "長照社福",
    "action_type": "新聞稿",
    "title": "要求提高暑期社福據點量能",
    "summary": "針對暑期家庭照顧壓力，要求提高社福據點服務量能與支援密度。",
    "alignment": "符合",
    "weight": "2",
    "source_id": "mvp-seed-demo",
    "source_name": "MVP 種子資料（待查證）",
    "source_url": "",
    "source_file": "",
    "review_status": "needs_review",
    "notes": "由 MVP 示範資料移入 2026-06 第一批行動資料；需補正式來源連結"
  }
];
