window.MVP_PLEDGES_2022 = [
  {
    "pledge_id": "pledge-2022-banqiao-lin-guochun-justice",
    "representative_id": "lin_guochun",
    "representative_name": "林國春",
    "candidate_no": "1",
    "issue_id": "justice",
    "issue_label": "治安詐騙",
    "pledge_summary": "反對廢除死刑並主張速審速決；酒駕與毒品零容忍；監督食安法規執行。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/lin_guochun.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-lin-guochun-transport",
    "representative_id": "lin_guochun",
    "representative_name": "林國春",
    "candidate_no": "1",
    "issue_id": "transport",
    "issue_label": "交通行人",
    "pledge_summary": "整治道路交通標誌與標線規劃，改善交通壅塞。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/lin_guochun.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-lin-guochun-care",
    "representative_id": "lin_guochun",
    "representative_name": "林國春",
    "candidate_no": "1",
    "issue_id": "care",
    "issue_label": "長照社福",
    "pledge_summary": "增設長照服務機構並建置友善安養環境。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/lin_guochun.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-lin-guochun-housing",
    "representative_id": "lin_guochun",
    "representative_name": "林國春",
    "candidate_no": "1",
    "issue_id": "housing",
    "issue_label": "居住都更",
    "pledge_summary": "提升居住品質、加速危老建築改善，並活化閒置空間作青年社宅、放寬入住資格以減輕租屋壓力。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/lin_guochun.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-lin-guochun-labor",
    "representative_id": "lin_guochun",
    "representative_name": "林國春",
    "candidate_no": "1",
    "issue_id": "labor",
    "issue_label": "地方建設",
    "pledge_summary": "廣設共融式遊具與特色公園，改善纜線與市容景觀，並推動智慧城市與國際能見度。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/lin_guochun.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-liu-meifang-education",
    "representative_id": "liu_meifang",
    "representative_name": "劉美芳",
    "candidate_no": "2",
    "issue_id": "education",
    "issue_label": "托育教育",
    "pledge_summary": "推動國家兒童未來館、程式與語言教育、公托中心與公立附設幼兒園，並優化校舍補強與老舊校舍改建。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/liu_meifang.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-liu-meifang-care",
    "representative_id": "liu_meifang",
    "representative_name": "劉美芳",
    "candidate_no": "2",
    "issue_id": "care",
    "issue_label": "長照社福",
    "pledge_summary": "設置專款基金補貼青年與弱勢族群租金，優化長者照護並推廣優質課程。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/liu_meifang.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-liu-meifang-energy",
    "representative_id": "liu_meifang",
    "representative_name": "劉美芳",
    "candidate_no": "2",
    "issue_id": "energy",
    "issue_label": "市場商圈",
    "pledge_summary": "發展新創事業與招商，增加就業機會，並爭取建置新北表演中心推廣藝文活動。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/liu_meifang.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-liu-meifang-labor",
    "representative_id": "liu_meifang",
    "representative_name": "劉美芳",
    "candidate_no": "2",
    "issue_id": "labor",
    "issue_label": "地方建設",
    "pledge_summary": "改善污水下水道、推動老舊社區都更、市容與電纜地下化、停車空間、公園改建及資訊局設置。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/liu_meifang.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-tseng-huanjia-labor",
    "representative_id": "tseng_huanjia",
    "representative_name": "曾煥嘉",
    "candidate_no": "3",
    "issue_id": "labor",
    "issue_label": "地方建設",
    "pledge_summary": "傾聽在地聲音、迅速服務民生，督促市府預算執行並改善企業投資環境。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/tseng_huanjia.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-tseng-huanjia-housing",
    "representative_id": "tseng_huanjia",
    "representative_name": "曾煥嘉",
    "candidate_no": "3",
    "issue_id": "housing",
    "issue_label": "居住都更",
    "pledge_summary": "積極推行板橋都更計畫並提升市民生活品質。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/tseng_huanjia.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-tseng-huanjia-care",
    "representative_id": "tseng_huanjia",
    "representative_name": "曾煥嘉",
    "candidate_no": "3",
    "issue_id": "care",
    "issue_label": "長照社福",
    "pledge_summary": "加強弱勢家庭與身心障礙福利服務。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/tseng_huanjia.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-tseng-huanjia-justice",
    "representative_id": "tseng_huanjia",
    "representative_name": "曾煥嘉",
    "candidate_no": "3",
    "issue_id": "justice",
    "issue_label": "治安詐騙",
    "pledge_summary": "爭取警消權益、提升救災設備，並要求增加社區監視器以維護居民生命財產安全。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/tseng_huanjia.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-tseng-huanjia-transport",
    "representative_id": "tseng_huanjia",
    "representative_name": "曾煥嘉",
    "candidate_no": "3",
    "issue_id": "transport",
    "issue_label": "交通行人",
    "pledge_summary": "持續加速板橋地區地下停車場設立，解決停車位不足。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/tseng_huanjia.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-chou-shengkao-labor",
    "representative_id": "chou_shengkao",
    "representative_name": "周勝考",
    "candidate_no": "8",
    "issue_id": "labor",
    "issue_label": "地方建設",
    "pledge_summary": "爭取釋出公有空間、增加休閒運動空間，並推動公園、校舍、公有空間與地下停車場等公共建設。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/chou_shengkao.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-chou-shengkao-care",
    "representative_id": "chou_shengkao",
    "representative_name": "周勝考",
    "candidate_no": "8",
    "issue_id": "care",
    "issue_label": "長照社福",
    "pledge_summary": "持續推動老人長照政策，提高老人津貼與年長者生活品質，並爭取弱勢與勞工權益。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/chou_shengkao.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-chou-shengkao-education",
    "representative_id": "chou_shengkao",
    "representative_name": "周勝考",
    "candidate_no": "8",
    "issue_id": "education",
    "issue_label": "托育教育",
    "pledge_summary": "推動國中小教室增設冷氣、公共托育中心、公私幼兒園雙軌平衡與幼兒園福利。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/chou_shengkao.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-chou-shengkao-transport",
    "representative_id": "chou_shengkao",
    "representative_name": "周勝考",
    "candidate_no": "8",
    "issue_id": "transport",
    "issue_label": "交通行人",
    "pledge_summary": "結合新建公共工程爭取地下停車場共構，紓解停車空間不足並保障機車停放權益。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/chou_shengkao.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-tai-weishan-education",
    "representative_id": "tai_weishan",
    "representative_name": "戴瑋姍",
    "candidate_no": "6",
    "issue_id": "education",
    "issue_label": "托育教育",
    "pledge_summary": "持續推動兒童醫院，重視早期治療與兒童健康；增設公托、公幼及非營利幼兒園以減輕家長負擔。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/tai_weishan.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-tai-weishan-housing",
    "representative_id": "tai_weishan",
    "representative_name": "戴瑋姍",
    "candidate_no": "6",
    "issue_id": "housing",
    "issue_label": "居住都更",
    "pledge_summary": "加速都更與老城市翻新，興建青年社會住宅以實現居住正義。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/tai_weishan.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-tai-weishan-transport",
    "representative_id": "tai_weishan",
    "representative_name": "戴瑋姍",
    "candidate_no": "6",
    "issue_id": "transport",
    "issue_label": "交通行人",
    "pledge_summary": "打造人本交通城市，提升行人、自行車與機車用路權，並推動軌道建設、地下停車場與微笑單車站點。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/tai_weishan.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-tai-weishan-care",
    "representative_id": "tai_weishan",
    "representative_name": "戴瑋姍",
    "candidate_no": "6",
    "issue_id": "care",
    "issue_label": "長照社福",
    "pledge_summary": "免費裝假牙、提升敬老卡福利，整合長照資源以協助子女照顧長者。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/tai_weishan.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-tai-weishan-justice",
    "representative_id": "tai_weishan",
    "representative_name": "戴瑋姍",
    "candidate_no": "6",
    "issue_id": "justice",
    "issue_label": "治安詐騙",
    "pledge_summary": "充實警消與清潔隊裝備，提升第一線工作量能。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/tai_weishan.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-tai-weishan-energy",
    "representative_id": "tai_weishan",
    "representative_name": "戴瑋姍",
    "candidate_no": "6",
    "issue_id": "energy",
    "issue_label": "市場商圈",
    "pledge_summary": "結合觀光與商圈再造，繁榮老城區並保存推廣古蹟歷史建築。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "1",
    "source_crop": "sources/crops/tai_weishan.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-yamada-mai-labor",
    "representative_id": "yamada_mai",
    "representative_name": "山田摩衣",
    "candidate_no": "15",
    "issue_id": "labor",
    "issue_label": "地方建設",
    "pledge_summary": "增設青年創業基地、共享辦公室與新創團隊輔導，整合青年局諮詢、空間與資金補助。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "2",
    "source_crop": "sources/crops/yamada_mai.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-yamada-mai-education",
    "representative_id": "yamada_mai",
    "representative_name": "山田摩衣",
    "candidate_no": "15",
    "issue_id": "education",
    "issue_label": "托育教育",
    "pledge_summary": "增加公托、公幼比例與普及率，降低延長照顧與課後安親費用，並增設特色公園與小型閒置空間據點。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "2",
    "source_crop": "sources/crops/yamada_mai.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-yamada-mai-care",
    "representative_id": "yamada_mai",
    "representative_name": "山田摩衣",
    "candidate_no": "15",
    "issue_id": "care",
    "issue_label": "長照社福",
    "pledge_summary": "督促落實優質且平價的長照服務，讓長者與失能者就近照顧、在地照顧。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "2",
    "source_crop": "sources/crops/yamada_mai.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-yamada-mai-transport",
    "representative_id": "yamada_mai",
    "representative_name": "山田摩衣",
    "candidate_no": "15",
    "issue_id": "transport",
    "issue_label": "交通行人",
    "pledge_summary": "打造智慧交通系統、改善停車與候車標示，拓寬人行道、強化視覺引導，並推動車流分流。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "2",
    "source_crop": "sources/crops/yamada_mai.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-yamada-mai-justice",
    "representative_id": "yamada_mai",
    "representative_name": "山田摩衣",
    "candidate_no": "15",
    "issue_id": "justice",
    "issue_label": "治安詐騙",
    "pledge_summary": "推動動物友善公園與保險，健全動保法令與生命教育。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "2",
    "source_crop": "sources/crops/yamada_mai.png",
    "review_status": "needs_review",
    "notes": "此列暫以現有議題對應動保/公共安全，後續可新增動保議題"
  },
  {
    "pledge_id": "pledge-2022-banqiao-yamada-mai-energy",
    "representative_id": "yamada_mai",
    "representative_name": "山田摩衣",
    "candidate_no": "15",
    "issue_id": "energy",
    "issue_label": "市場商圈",
    "pledge_summary": "要求板橋公有市場攤商與購物者便利及舒適度提升，並推動電線電纜地下化與公共環境改善。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "2",
    "source_crop": "sources/crops/yamada_mai.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-huang-shujun-transport",
    "representative_id": "huang_shujun",
    "representative_name": "黃淑君",
    "candidate_no": "18",
    "issue_id": "transport",
    "issue_label": "交通行人",
    "pledge_summary": "檢討號誌、待轉區、人行道、都計道路設置與交通安全，針對不同區域提出對策。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "3",
    "source_crop": "sources/crops/huang_shujun.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-huang-shujun-education",
    "representative_id": "huang_shujun",
    "representative_name": "黃淑君",
    "candidate_no": "18",
    "issue_id": "education",
    "issue_label": "托育教育",
    "pledge_summary": "增設公托與非營利幼兒園，建立保母媒合平台，落實兒童照顧與高風險家庭通報。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "3",
    "source_crop": "sources/crops/huang_shujun.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-huang-shujun-justice",
    "representative_id": "huang_shujun",
    "representative_name": "黃淑君",
    "candidate_no": "18",
    "issue_id": "justice",
    "issue_label": "治安詐騙",
    "pledge_summary": "重視食品安全、食品製程查核、食農教育及醫療環境改善。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "3",
    "source_crop": "sources/crops/huang_shujun.png",
    "review_status": "needs_review",
    "notes": "此列含食安與公共健康，後續可拆分食安/醫療議題"
  },
  {
    "pledge_id": "pledge-2022-banqiao-huang-shujun-care",
    "representative_id": "huang_shujun",
    "representative_name": "黃淑君",
    "candidate_no": "18",
    "issue_id": "care",
    "issue_label": "長照社福",
    "pledge_summary": "推動地方婦幼門診、心理照護機制與生育支持，降低家庭照顧壓力。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "3",
    "source_crop": "sources/crops/huang_shujun.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-shih-yiyou-care",
    "representative_id": "shih_yiyou",
    "representative_name": "石一佑",
    "candidate_no": "21",
    "issue_id": "care",
    "issue_label": "長照社福",
    "pledge_summary": "提高生育補助、育兒津貼，推動婦女就業創業平台、銀髮照護據點與長照機構。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "3",
    "source_crop": "sources/crops/shih_yiyou.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-shih-yiyou-education",
    "representative_id": "shih_yiyou",
    "representative_name": "石一佑",
    "candidate_no": "21",
    "issue_id": "education",
    "issue_label": "托育教育",
    "pledge_summary": "依各區幼兒人口調整公托、公幼級數，強化師資培育與學童品德教育，改善托育品質。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "3",
    "source_crop": "sources/crops/shih_yiyou.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-shih-yiyou-labor",
    "representative_id": "shih_yiyou",
    "representative_name": "石一佑",
    "candidate_no": "21",
    "issue_id": "labor",
    "issue_label": "地方建設",
    "pledge_summary": "增加青年創業基地、招商與就業機會，強化職訓與媒合以提升就業率。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "3",
    "source_crop": "sources/crops/shih_yiyou.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-shih-yiyou-transport",
    "representative_id": "shih_yiyou",
    "representative_name": "石一佑",
    "candidate_no": "21",
    "issue_id": "transport",
    "issue_label": "交通行人",
    "pledge_summary": "改善道路與標線、增設左轉附加車道與標示牌。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "3",
    "source_crop": "sources/crops/shih_yiyou.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-shih-yiyou-housing",
    "representative_id": "shih_yiyou",
    "representative_name": "石一佑",
    "candidate_no": "21",
    "issue_id": "housing",
    "issue_label": "居住都更",
    "pledge_summary": "合理調整公辦都更比例、增加都更誘因、推動危老防災型都更，並將囤房稅用於青年與弱勢租金補貼、健全租屋市場。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "3",
    "source_crop": "sources/crops/shih_yiyou.png",
    "review_status": "needs_review",
    "notes": "官方公報初步整理"
  },
  {
    "pledge_id": "pledge-2022-banqiao-shih-yiyou-justice",
    "representative_id": "shih_yiyou",
    "representative_name": "石一佑",
    "candidate_no": "21",
    "issue_id": "justice",
    "issue_label": "治安詐騙",
    "pledge_summary": "主張市議會會議紀錄與都更資訊公開透明，推動參與式民主讓市民參與規劃決策。",
    "source_pdf": "sources/cec-2022-new-taipei-district-05-banqiao.pdf",
    "source_page": "3",
    "source_crop": "sources/crops/shih_yiyou.png",
    "review_status": "needs_review",
    "notes": "此列對應治理透明，後續可新增透明治理議題"
  }
];
